"""criar tabelas carga e carga item

Revision ID: 20362a1fb1b3
Revises: 98243fb1d9ad
Create Date: 2026-06-10 14:33:35.115947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20362a1fb1b3'
down_revision: Union[str, Sequence[str], None] = '98243fb1d9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_mensal_id', sa.Integer(), nullable=False),
    sa.Column('familia', sa.String(length=150), nullable=False),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('minutagem_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plano_mensal_id'], ['plano_mensal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carga_id'), 'carga', ['id'], unique=False)
    op.create_table('carga_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('minutagem', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['carga.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carga_item_id'), 'carga_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carga_item_id'), table_name='carga_item')
    op.drop_table('carga_item')
    op.drop_index(op.f('ix_carga_id'), table_name='carga')
    op.drop_table('carga')
    # ### end Alembic commands ###
