"""criar tabelas plano mensal

Revision ID: 98243fb1d9ad
Revises: a409355fe133
Create Date: 2026-06-10 14:29:04.598926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98243fb1d9ad'
down_revision: Union[str, Sequence[str], None] = 'a409355fe133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_por', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_mensal_id'), 'plano_mensal', ['id'], unique=False)
    op.create_table('plano_mensal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_mensal_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plano_mensal_id'], ['plano_mensal.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_mensal_item_id'), 'plano_mensal_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plano_mensal_item_id'), table_name='plano_mensal_item')
    op.drop_table('plano_mensal_item')
    op.drop_index(op.f('ix_plano_mensal_id'), table_name='plano_mensal')
    op.drop_table('plano_mensal')
    # ### end Alembic commands ###
