"""criar tabela maquina

Revision ID: a409355fe133
Revises: beb7f08c00a7
Create Date: 2026-06-10 14:26:42.476428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a409355fe133'
down_revision: Union[str, Sequence[str], None] = 'beb7f08c00a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('meta_cargas_dia', sa.Integer(), nullable=False),
    sa.Column('tempo_disponivel_dia', sa.Integer(), nullable=False),
    sa.Column('tempo_carga', sa.Integer(), nullable=False),
    sa.Column('capacidade_pecas', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquina_id'), 'maquina', ['id'], unique=False)
    op.create_index(op.f('ix_maquina_nome'), 'maquina', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maquina_nome'), table_name='maquina')
    op.drop_index(op.f('ix_maquina_id'), table_name='maquina')
    op.drop_table('maquina')
    # ### end Alembic commands ###
