"""criar tabelas programacao diaria

Revision ID: d2204560b40c
Revises: 20362a1fb1b3
Create Date: 2026-06-10 14:35:08.280889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2204560b40c'
down_revision: Union[str, Sequence[str], None] = '20362a1fb1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programacao_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_programacao', sa.Date(), nullable=False),
    sa.Column('plano_mensal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plano_mensal_id'], ['plano_mensal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacao_diaria_id'), 'programacao_diaria', ['id'], unique=False)
    op.create_table('programacao_diaria_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programacao_diaria_id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('sequencia_carga', sa.Integer(), nullable=False),
    sa.Column('minutagem', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['carga.id'], ),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['programacao_diaria_id'], ['programacao_diaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacao_diaria_item_id'), 'programacao_diaria_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programacao_diaria_item_id'), table_name='programacao_diaria_item')
    op.drop_table('programacao_diaria_item')
    op.drop_index(op.f('ix_programacao_diaria_id'), table_name='programacao_diaria')
    op.drop_table('programacao_diaria')
    # ### end Alembic commands ###
